### ISSUE TITLE
Azure avatar

### ISSUE THREAD

**Issue by Hanu4507** [hacktronaut/azure-avatar-demo#1]
After giving all the details I try to run the code. While running the code I am getting a WebSocket connection error. Also, WebRTCConnection is not connected properly. How can I solve this issue?

**Comment by hacktronaut** [comment]
Can you share the error message or screenshots?. Are you behind a proxy ?

**Comment by Hanu4507** [comment]
> Can you share the error message or screenshots?. Are you behind a proxy ?

It's working fine now. Thank you for providing this valuable code......

**Comment by hacktronaut** [comment]
That's great @Hanu4507  :smile:  What was the issue ?

**Comment by Hanu4507** [comment]
> That's great @Hanu4507 😄 What was the issue ?

I got a WebSocket error. Because WebRTCConnection is not connected properly. 
So, I cloned the GitHub code again and ran the code at the time it connected to WebRTCConnection but it did not show any avatar. Then I changed the iceUrl prefix to "turn" and now it's working fine.

**Comment by hacktronaut** [comment]
Great ! I am closing this issue now. Happy coding :smile:
