### ISSUE TITLE
Avatar failed to start

### ISSUE THREAD

**Issue by sumitsarraf** [hacktronaut/azure-avatar-demo#4]
[2024-09-17T09:48:35.973Z] Avatar failed to start. Error: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by oferpaster** [comment]
Same problem here

**Comment by oferpaster** [comment]
I think I found the problem, the text-to-speech avatar feature is only available in these service regions: West US 2, West Europe, and Southeast Asia.

**Comment by hacktronaut** [comment]
@oferpaster Yeah that could be the issue. I have face the same issue when I was trying with different regions. I chose only WestUS2 region and it works fine for me.

**Comment by Alex-Beh** [comment]
Hi @hacktronaut  

What is the endpoint that I should fill here?
![image](https://github.com/user-attachments/assets/3ea95acf-dec8-49b3-86d5-914b0fbdef7d)

This??
![image](https://github.com/user-attachments/assets/f28a6e58-7137-432f-93e9-159e49275d71)

**Comment by hacktronaut** [comment]
Yeah give the speech key and try.
